version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: stockwatch_postgres
    environment:
      POSTGRES_DB: stockwatch
      POSTGRES_USER: stockwatch_user
      POSTGRES_PASSWORD: stockwatch_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U stockwatch_user -d stockwatch" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
