# Exported from Render on 2026-06-18T03:51:41Z
version: "1"
databases:
- name: stockwatch-db
  databaseName: stockwatch_db_gak1
  user: stockwatch_db_gak1_user
  plan: free
  region: virginia
  ipAllowList: []
  postgresMajorVersion: "16"


services:
  - type: web
    name: stockwatch
    runtime: python
    plan: free
    region: virginia
    buildCommand: pip install -r requirements.txt
    startCommand: FLASK_APP=wsgi:app flask db upgrade && gunicorn --bind 0.0.0.0:$PORT wsgi:app --timeout 120 --workers 1
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: FLASK_APP
        value: wsgi:app
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: stockwatch-db
          property: connectionString
      - key: POLYGON_API_KEY
        sync: false
