"""add portfolio_transaction table

Revision ID: e386e388be04
Revises: 7e3c96963ae6
Create Date: 2026-07-17 16:18:31.866685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e386e388be04'
down_revision = '7e3c96963ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('executed_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("side IN ('BUY', 'SELL')", name='ck_transaction_side'),
    sa.CheckConstraint('price >= 0', name='ck_transaction_price_non_negative'),
    sa.CheckConstraint('quantity > 0', name='ck_transaction_quantity_positive'),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_transaction_stock_id'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_transaction_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_transaction_user_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_transaction_stock_id'))

    op.drop_table('portfolio_transaction')
    # ### end Alembic commands ###
